create table if not exists car (car_id  bigserial not null, car_make varchar(255), color varchar(255), create_date timestamp, engine_capacity varchar(255), mileage varchar(255), modify_date timestamp, power varchar(255), production_year timestamp, type varchar(255), version int8, facility_id int8, primary key (car_id));
create table if not exists client (client_id  bigserial not null, address varchar(255), birthday timestamp, credit_card int4 not null, version int8, primary key (client_id));
create table if not exists facility (facility_id  bigserial not null, address varchar(255), contact varchar(255), version int8, primary key (facility_id));
create table if not exists rental (rental_id  bigserial not null, deposit_amount int4 not null, end_date timestamp, start_date timestamp, version int8, car_id int8, client_id int8, rental_facility_id int8, return_facility_id int8, primary key (rental_id));
create table if not exists worker (worker_id  bigserial not null, position varchar(255), version int8, facility_id int8, primary key (worker_id));
create table if not exists worker_car (worker_id int8 not null, car_id int8 not null);
alter table car drop constraint if exists facility_fk;
alter table car add constraint facility_fk foreign key (facility_id) references facility;
alter table rental drop constraint if exists car_fk;
alter table rental add constraint car_fk foreign key (car_id) references car;
alter table rental drop constraint if exists client_fk;
alter table rental add constraint client_fk foreign key (client_id) references client;
alter table rental drop constraint if exists rental_facility_fk;
alter table rental add constraint rental_facility_fk foreign key (rental_facility_id) references facility;
alter table rental drop constraint if exists return_facility_fk;
alter table rental add constraint return_facility_fk foreign key (return_facility_id) references facility;
alter table worker drop constraint if exists w_facility_fk;
alter table worker add constraint w_facility_fk foreign key (facility_id) references facility;
alter table worker_car drop constraint if exists w_car_fk;
alter table worker_car add constraint w_car_fk foreign key (car_id) references car;
alter table worker_car drop constraint if exists c_worker_fk;
alter table worker_car add constraint c_worker_fk foreign key (worker_id) references worker;